name: Development Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy-develop:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ENVIRONMENT: "development"
          VITE_LOGGING_LEVEL: "debug"

      - name: Create build artifact
        id: create_artifact
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          cd dist
          zip -r ../taskhub-dev-$TIMESTAMP.zip .
          cd ..
          echo "Build timestamp: $(date)" > build-info.txt
          echo "Commit: ${{ github.sha }}" >> build-info.txt
          echo "Branch: develop" >> build-info.txt
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: Upload build artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: taskhub-dev-build
          path: |
            taskhub-dev-*.zip
            build-info.txt
          retention-days: 30

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make script executable
        run: chmod +x .github/scripts/upload-dev-artifact.sh

      - name: Upload build to Azure Blob Storage
        id: upload_artifact
        run: |
          ./.github/scripts/upload-dev-artifact.sh \
            ${{ steps.create_artifact.outputs.timestamp }} \
            ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            ${{ github.sha }}

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          skip_app_build: true

      - name: Post deployment notification
        if: success()
        run: |
          echo "🚀 Successfully deployed to development environment"
          echo "URL: https://green-grass-07a60cd00.6.azurestaticapps.net"
          echo "Build artifact: taskhub-dev-${{ steps.create_artifact.outputs.timestamp }}.zip stored in Azure Blob Storage"
          echo "Download link: ${{ steps.upload_artifact.outputs.download_url }}"
