name: Sync develop after release

on:
  push:
    branches:
      - main
    paths:
      - "package.json" # Assuming semantic-release updates this file

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important to fetch all history

      - name: Check if release commit
        id: check_release
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$COMMIT_MSG" == *"chore(release)"* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create PR to sync develop
        if: steps.check_release.outputs.is_release == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync develop with main after release"
          branch: chore/sync-develop-after-release
          delete-branch: true
          title: "chore: sync develop with main after release"
          body: |
            This PR syncs the develop branch with main after a release.

            Automated PR to keep develop up-to-date.
          base: develop
